def build_v2_1_22_status():
    return {
        "stage":"BROKER_INTEGRATION_V2_1_22_ALPACA_PAPER_BOUNDED_EXECUTION_BRIDGE",
        "status":"PASS_DEVELOPMENT_COMPLETE",
        "base_commit":"f72ebec2",
        "v2_1_21_current_ready_required":True,
        "v2_1_17_current_evidence_binding_required":True,
        "existing_paper_execution_profile_reused":True,
        "existing_paper_service_preflight_reused":True,
        "existing_alpaca_paper_adapter_reused":True,
        "existing_canonical_selector_reused":True,
        "new_broker_adapter_created":False,
        "new_order_request_engine_created":False,
        "canonical_min_confidence":"0.75",
        "canonical_min_reward_risk":"1.0",
        "maximum_validation_notional":25.0,
        "maximum_bridge_submissions_per_session":1,
        "manual_paper_arm_required":True,
        "explicit_submit_phrase_required":True,
        "one_time_evidence_consumption_guard":True,
        "existing_open_position_guard":True,
        "install_test_paper_orders":0,
        "live_order_submission_allowed":False,
        "etrade_write_allowed":False,
    }
