from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path


EXPECTED_ENGINE="multi_timeframe_ai.engine.analyze_symbol"
EXPECTED_SELECTOR="paper_autonomous_execution.signals.select_candidate"
EXPECTED_MIN_CONFIDENCE=Decimal("0.75")
EXPECTED_MIN_REWARD_RISK=Decimal("1.0")


def _sha256_file(path:Path):
    h=hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""):
            h.update(chunk)
    return h.hexdigest()


def _decimal(value):
    try:
        return Decimal(str(value))
    except (InvalidOperation,ValueError,TypeError):
        return None


def _canonical_confidence(item):
    calibration=item.get("confidence_calibration") or {}
    value=calibration.get("calibrated_confidence")
    if value is None:
        value=item.get("confidence")
    return _decimal(value)


class CanonicalRewardRiskProvenanceBridgeV2120:
    """
    Read-only provenance bridge.

    Source A:
      V2.1.16 fresh eligible evidence.

    Source B:
      Existing real-market canonical multi-timeframe shadow snapshot generated by
      multi_timeframe_ai.engine.analyze_symbol and selected by
      paper_autonomous_execution.signals.select_candidate.

    This stage does not calculate a replacement reward/risk formula.
    It copies the existing canonical engine's reward_risk only when:
      - canonical report contract matches expected engine/selector/thresholds;
      - symbol exists in canonical analyses;
      - canonical action matches the evidence signal side;
      - calibrated confidence and reward_risk are present.

    No broker network or order submission occurs.
    """

    def __init__(self,root):
        self.root=Path(root)
        self.evidence_source=(
            self.root/"runtime"/"fresh_eligible_signal_evidence_v2_1_16"/
            "eligible_signal_evidence.jsonl"
        )
        self.canonical_snapshot=(
            self.root/"runtime"/"real_market_multitimeframe_shadow"/
            "latest_real_market_shadow.json"
        )
        self.runtime_dir=(
            self.root/"runtime"/"canonical_reward_risk_provenance_v2_1_20"
        )
        self.runtime_dir.mkdir(parents=True,exist_ok=True)
        self.output_ledger=self.runtime_dir/"enriched_evidence.jsonl"
        self.latest_output=self.runtime_dir/"latest_enriched_evidence.json"

    def _existing_keys(self):
        keys=set()
        if not self.output_ledger.exists():
            return keys
        for line in self.output_ledger.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            row=json.loads(line)
            if row.get("evidence_key"):
                keys.add(row["evidence_key"])
        return keys

    def _load_canonical(self):
        if not self.canonical_snapshot.exists():
            return None,{
                "status":"WAITING_FOR_CANONICAL_REAL_MARKET_SNAPSHOT",
                "reason":"CANONICAL_SNAPSHOT_MISSING",
            }

        report=json.loads(
            self.canonical_snapshot.read_text(encoding="utf-8")
        )
        reasons=[]

        if report.get("canonical_engine")!=EXPECTED_ENGINE:
            reasons.append("CANONICAL_ENGINE_MISMATCH")
        if report.get("canonical_selector")!=EXPECTED_SELECTOR:
            reasons.append("CANONICAL_SELECTOR_MISMATCH")

        thresholds=report.get("thresholds") or {}
        min_conf=_decimal(thresholds.get("min_confidence"))
        min_rr=_decimal(thresholds.get("min_reward_risk"))
        if min_conf!=EXPECTED_MIN_CONFIDENCE:
            reasons.append("CANONICAL_CONFIDENCE_THRESHOLD_MISMATCH")
        if min_rr!=EXPECTED_MIN_REWARD_RISK:
            reasons.append("CANONICAL_REWARD_RISK_THRESHOLD_MISMATCH")

        mode=str(report.get("mode") or "")
        if mode!="SHADOW_ANALYSIS_ONLY":
            reasons.append("CANONICAL_SNAPSHOT_MODE_MISMATCH")

        analyses=list(report.get("analyses") or [])
        if not analyses:
            reasons.append("CANONICAL_ANALYSES_EMPTY")

        if reasons:
            return None,{
                "status":"BLOCKED_CANONICAL_SOURCE_CONTRACT",
                "reason":";".join(reasons),
                "reasons":reasons,
            }

        by_symbol={}
        for item in analyses:
            symbol=str(item.get("symbol") or "").upper().strip()
            if symbol:
                by_symbol[symbol]=item

        provenance={
            "canonical_snapshot_path":str(self.canonical_snapshot),
            "canonical_snapshot_sha256":_sha256_file(self.canonical_snapshot),
            "canonical_snapshot_generated_at_utc":report.get("generated_at_utc"),
            "canonical_source_dataset":report.get("source_dataset"),
            "canonical_engine":report.get("canonical_engine"),
            "canonical_selector":report.get("canonical_selector"),
            "canonical_min_confidence":str(EXPECTED_MIN_CONFIDENCE),
            "canonical_min_reward_risk":str(EXPECTED_MIN_REWARD_RISK),
            "provenance_kind":"EXISTING_CANONICAL_ANALYSIS_OUTPUT",
            "reward_risk_formula_recomputed":False,
        }
        return (by_symbol,provenance),None

    @staticmethod
    def _enrich_signal(signal,canonical_item,provenance):
        symbol=str(signal.get("symbol") or "").upper().strip()
        side=str(signal.get("side") or "").upper().strip()
        canonical_action=str(
            canonical_item.get("action") or canonical_item.get("side") or ""
        ).upper().strip()

        reasons=[]
        if canonical_action!=side:
            reasons.append("CANONICAL_ACTION_SIDE_MISMATCH")

        rr=_decimal(canonical_item.get("reward_risk"))
        confidence=_canonical_confidence(canonical_item)

        if rr is None:
            reasons.append("CANONICAL_REWARD_RISK_MISSING")
        if confidence is None:
            reasons.append("CANONICAL_CALIBRATED_CONFIDENCE_MISSING")

        enriched=dict(signal)
        enriched["generic_source_confidence"]=str(
            signal.get("source_confidence") or ""
        )
        enriched["canonical_action"]=canonical_action
        enriched["canonical_calibrated_confidence"]=(
            None if confidence is None else str(confidence)
        )
        enriched["source_confidence"]=(
            None if confidence is None else str(confidence)
        )
        enriched["source_reward_risk"]=(
            None if rr is None else str(rr)
        )
        enriched["canonical_reward_risk"]=(
            None if rr is None else str(rr)
        )
        enriched["canonical_rr_provenance"]=dict(provenance)
        enriched["canonical_provenance_valid"]=len(reasons)==0
        enriched["canonical_provenance_reasons"]=reasons
        return enriched,reasons

    def build(self):
        if not self.evidence_source.exists():
            return {
                "status":"WAITING_FOR_V2_1_16_EVIDENCE",
                "source_rows":0,
                "new_rows":0,
                "blocked_rows":0,
                "broker_orders_submitted":0,
                "production_order_submission":False,
                "live_trading":False,
            }

        canonical,error=self._load_canonical()
        if error:
            return {
                **error,
                "source_rows":0,
                "new_rows":0,
                "blocked_rows":0,
                "broker_orders_submitted":0,
                "production_order_submission":False,
                "live_trading":False,
            }

        by_symbol,base_provenance=canonical
        existing=self._existing_keys()
        source_rows=new_rows=duplicate_rows=blocked_rows=0
        latest=None

        for line in self.evidence_source.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            source_rows+=1
            evidence=json.loads(line)
            key=str(evidence.get("evidence_key") or "").strip()
            if not key:
                raise RuntimeError("V2.1.16 evidence missing evidence_key")
            if key in existing:
                duplicate_rows+=1
                continue

            signals=list(evidence.get("eligible_signals") or [])
            enriched_signals=[]
            row_reasons=[]

            for idx,signal in enumerate(signals,1):
                symbol=str(signal.get("symbol") or "").upper().strip()
                canonical_item=by_symbol.get(symbol)
                if canonical_item is None:
                    enriched=dict(signal)
                    enriched["canonical_provenance_valid"]=False
                    enriched["canonical_provenance_reasons"]=[
                        "CANONICAL_SYMBOL_ANALYSIS_MISSING"
                    ]
                    enriched_signals.append(enriched)
                    row_reasons.append(
                        f"SIGNAL_{idx}_CANONICAL_SYMBOL_ANALYSIS_MISSING"
                    )
                    continue

                provenance=dict(base_provenance)
                provenance["symbol"]=symbol
                provenance["canonical_analysis_fingerprint_sha256"]=hashlib.sha256(
                    json.dumps(
                        canonical_item,
                        sort_keys=True,
                        separators=(",",":"),
                        default=str,
                    ).encode("utf-8")
                ).hexdigest()

                enriched,reasons=self._enrich_signal(
                    signal,canonical_item,provenance
                )
                enriched_signals.append(enriched)
                row_reasons.extend(
                    f"SIGNAL_{idx}_{reason}" for reason in reasons
                )

            valid=bool(signals) and len(row_reasons)==0
            if not valid:
                blocked_rows+=1

            row={
                **evidence,
                "stage":
                    "BROKER_INTEGRATION_V2_1_20_CANONICAL_REWARD_RISK_PROVENANCE_BRIDGE",
                "source_stage":evidence.get("stage"),
                "eligible_signals":enriched_signals,
                "canonical_reward_risk_provenance_valid":valid,
                "canonical_reward_risk_provenance_reasons":row_reasons,
                "canonical_min_confidence":str(EXPECTED_MIN_CONFIDENCE),
                "canonical_min_reward_risk":str(EXPECTED_MIN_REWARD_RISK),
                "canonical_paper_gate_semantics":"CORRECTED_V2_1_19_1",
                "reward_risk_formula_recomputed":False,
                "market_data_fetch_from_stage":False,
                "etrade_oauth_started":False,
                "sandbox_preview_sent":False,
                "sandbox_place_sent":False,
                "broker_orders_submitted":0,
                "production_order_submission":False,
                "live_trading":False,
                "profitability_validated":False,
            }

            with self.output_ledger.open("a",encoding="utf-8") as f:
                f.write(json.dumps(row,sort_keys=True,ensure_ascii=False)+"\n")
            self.latest_output.write_text(
                json.dumps(row,indent=2,sort_keys=True,ensure_ascii=False),
                encoding="utf-8",
            )
            existing.add(key)
            new_rows+=1
            latest=row

        return {
            "status":"PASS_CANONICAL_REWARD_RISK_PROVENANCE_BRIDGE",
            "source_rows":source_rows,
            "new_rows":new_rows,
            "duplicate_rows":duplicate_rows,
            "blocked_rows":blocked_rows,
            "output_ledger":str(self.output_ledger),
            "latest_output":None if latest is None else str(self.latest_output),
            "reward_risk_formula_recomputed":False,
            "market_data_fetch_from_stage":False,
            "etrade_oauth_started":False,
            "sandbox_preview_sent":False,
            "sandbox_place_sent":False,
            "broker_orders_submitted":0,
            "production_order_submission":False,
            "live_trading":False,
        }
