def build_v2_1_20_status():
    return {
        "stage":"BROKER_INTEGRATION_V2_1_20_CANONICAL_REWARD_RISK_PROVENANCE_BRIDGE",
        "status":"PASS_DEVELOPMENT_COMPLETE",
        "base_commit":"a315dc5c",
        "v2_1_16_evidence_reused":True,
        "existing_canonical_analysis_reused":True,
        "canonical_engine":"multi_timeframe_ai.engine.analyze_symbol",
        "canonical_selector":"paper_autonomous_execution.signals.select_candidate",
        "canonical_min_confidence":"0.75",
        "canonical_min_reward_risk":"1.0",
        "reward_risk_formula_recomputed":False,
        "symbol_match_required":True,
        "action_side_match_required":True,
        "canonical_calibrated_confidence_required":True,
        "canonical_reward_risk_required":True,
        "sha256_provenance_binding":True,
        "v2_1_17_source_redirected_to_v2_1_20":True,
        "market_data_fetch_from_stage":False,
        "etrade_oauth_from_stage":False,
        "sandbox_preview_from_stage":False,
        "sandbox_place_from_stage":False,
        "broker_order_submission_from_stage":False,
        "production_order_post_allowed":False,
        "live_trading_enabled":False,
    }
