def build_etrade_sandbox_order_v2_1_2_status():
    return {
        "stage":"BROKER_INTEGRATION_V2_1_2_SANDBOX_PLACE_LEDGER_RECONCILIATION",
        "status":"PASS_DEVELOPMENT_COMPLETE",
        "development_status":"COMPLETE",
        "sandbox_place_supported":True,
        "explicit_place_confirmation_required":True,
        "order_ledger_supported":True,
        "status_reconciliation_supported":True,
        "reconciliation_modes":[
            "MATCHED",
            "SAMPLE_DATA_MISMATCH",
            "NOT_OBSERVED",
        ],
        "production_order_post_allowed":False,
        "live_trading_enabled":False,
        "profitability_validation":False,
        "real_execution_validation":False,
        "contracts":{
            "existing_v2_1_preview_place_pipeline_reused":True,
            "existing_v2_readonly_transport_reused":True,
            "canonical_broker_order_request_reused":True,
            "duplicate_order_engine_created":False,
            "runtime_ledger_gitignored":True,
            "account_id_stored_raw":False,
            "real_money_moved":False,
            "production_order_submission_performed":False,
        },
    }
