def build_v2_1_26_status():
    return {
        "stage":"BROKER_INTEGRATION_V2_1_26_FULL_ALPACA_PAPER_ROUND_TRIP_CYCLE",
        "status":"PASS_DEVELOPMENT_COMPLETE",
        "base_commit":"caf482b7",
        "v2_1_21_validator_reused":True,
        "v2_1_22_entry_reused":True,
        "v2_1_23_lifecycle_reused":True,
        "v2_1_25_exit_recovery_reused":True,
        "new_signal_engine_created":False,
        "new_broker_adapter_created":False,
        "new_exit_strategy_created":False,
        "recovery_first_state_machine":True,
        "durable_cycle_state":True,
        "maximum_paper_entries_per_cycle":1,
        "maximum_paper_exits_per_cycle":1,
        "dry_mode_default":True,
        "full_cycle_confirmation_required":True,
        "manual_paper_arm_still_required":True,
        "install_test_broker_network":False,
        "install_test_paper_orders":0,
        "install_test_live_orders":0,
        "live_trading_enabled":False,
        "next_stage":"V2.1.27_FINAL_EXIT_FILL_RECONCILIATION_AND_ROUND_TRIP_LEDGER",
    }
